### ISSUE TITLE
npm start give errors

### ISSUE THREAD

**Issue by stevies** [atom/electron-quick-start#20]
If I run 'npm install && npm start' I get error.  

Content of npm-debug.log is: 

>0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.14.7
3 info using node@v4.2.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart electron-quick-start@1.0.0
6 info start electron-quick-start@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info electron-quick-start@1.0.0 Failed to exec start script
9 verbose stack Error: electron-quick-start@1.0.0 start: `electron main.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:818:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid electron-quick-start@1.0.0
11 verbose cwd /home/dev/WebstormProjects/electron-quick-start
12 error Linux 2.6.32-504.8.1.el6.x86_64
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
14 error node v4.2.3
15 error npm  v2.14.7
16 error code ELIFECYCLE
17 error electron-quick-start@1.0.0 start: `electron main.js`
17 error Exit status 1
18 error Failed at the electron-quick-start@1.0.0 start script 'electron main.js'.
18 error This is most likely a problem with the electron-quick-start package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     electron main.js
18 error You can get their info via:
18 error     npm owner ls electron-quick-start
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
>

Tried various versions of node 4.x and 5.x and 0.12.x.  Same issue. 
Running on Centos 6.6

**Comment by stevies** [comment]
I now see that Centos is not in the list of supported OS.  I guess that it the problem for me.  I should have checked first.
