### ISSUE TITLE
Invalid install target version in package.json

### ISSUE THREAD

**Issue by theRobinator** [atom/electron-quick-start#34]
Performing the following steps from the README:
```
git clone https://github.com/atom/electron-quick-start
cd electron-quick-start
npm install
```

Gives me:
```
npm http GET https://registry.npmjs.org/electron-prebuilt
npm http 304 https://registry.npmjs.org/electron-prebuilt
npm ERR! Error: No compatible version found: electron-prebuilt@'^0.36.0'
npm ERR! Valid install targets:
npm ERR! ["0.24.0","0.25.0","0.25.1","0.25.1-1","0.25.2","0.25.2-1","0.25.3","0.25.3-1","0.25.3-2","0.26.0","0.26.1","0.27.0","0.27.1","0.27.2","0.27.3","0.28.0","0.28.1","0.28.2","0.28.3","0.29.0","0.29.1","0.29.2","0.30.0","0.30.1","0.30.2","0.30.3","0.30.4","0.30.5","0.31.0","0.30.6","0.31.1","0.31.2","0.32.0","0.32.1","0.32.2","0.32.3","0.33.0","0.33.1","0.30.7","0.33.2","0.30.8","0.33.3","0.33.4","0.33.5","0.33.6","0.33.7","0.33.8","0.33.9","0.34.0","0.34.1","0.34.2","0.34.3","0.35.0","0.35.1","0.34.4","0.34.5","0.35.2","0.35.3","0.35.4","0.36.0","0.36.1","0.36.2","0.35.5","0.36.3","0.35.6","0.36.4","0.36.5","0.36.6","0.36.7","0.36.8"]
npm ERR!     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:719:10)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:638:10
npm ERR!     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 15.0.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/robinkeller/Projects/cef/electron-quick-start
npm ERR! node -v v0.10.15
npm ERR! npm -v 1.3.5
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/robinkeller/Projects/cef/electron-quick-start/npm-debug.log
npm ERR! not ok code 0
```

**Comment by jlord** [comment]
There is a valid version, which it lists, so I'm not sure why you get this error.

Your versions of npm and Node.js are quite out of date, however, so perhaps you could upgrade and try again?

**Comment by jlord** [comment]
Closing now as it's gone stale. Please update/re-open if you have more information :sparkles:
