### ISSUE TITLE
Electron main.js works, npm start does not

### ISSUE THREAD

**Issue by quantumproducer** [atom/electron-quick-start#38]
```
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/quantum/electron-quick-start/node_modules/electron-prebuilt/path.txt'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.<anonymous> (/Users/quantum/electron-quick-start/node_modules/electron-prebuilt/index.js:4:42)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
▀ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.0.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! electron-quick-start@1.0.0 start: `electron main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-quick-start@1.0.0 start script 'electron main.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-quick-start package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron main.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-quick-start
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-quick-start
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
```

npm start gives me that message.

Contrary to that output, there is no `npm-debug.log` file, and `electron main.js` DOES work. Just npm start does not.

**Comment by quantumproducer** [comment]
npm-v: v4.0.0
electron -v v0.37.2

**Comment by quantumproducer** [comment]
This works in my original clone of electron-quick-start. Copying the folder or cloning to a different directory doesn't work.. some configuration is off?

**Comment by jlord** [comment]
If you clone it to another place you will need to run `npm install` again to add the dependencies to that new directory. Copying an already cloned and already `nom-install`-ed directory will also work.

**Comment by quantumproducer** [comment]
@jlord right, I did that.

```
draw.js			l3.wav			node_modules		static.wav
~/combo-electron:.npm install
▄ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▌ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▀ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▐ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░loadDep:inflight          ▌ ╢████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░loadDep:array-find-index  ▌ ╢█████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░loadDep:sntp              ▌ ╢█████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░loadAllDepsIntoIdealTree  ▐ ╢██████████████████████████████████████████████████postinstall:. → lifecycle ▐ ╢█████████████████████████████████████████████████runTopLevelLifecycles     ▄ ╢█████████████████████████████████████████████████~/combo-electron:.npm start

> electron-quick-start@1.0.0 start /Users/quantum/combo-electron
> electron main.js

▀ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░module.js:338
    throw err;
    ^

Error: Cannot find module './'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/quantum/combo-electron/node_modules/.bin/electron:3:16)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
▀ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.0.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! electron-quick-start@1.0.0 start: `electron main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-quick-start@1.0.0 start script 'electron main.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-quick-start package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron main.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-quick-start
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-quick-start
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/quantum/combo-electron/npm-debug.log
~/combo-electron:.;2A;2A;2A;2A
```

**Comment by zeke** [comment]
> electron main.js DOES work. Just npm start does not.

When you run `electron main.js`, you're likely using a version of `electron` that is installed globally on your system. When you run `npm start`, npm is first looking for a version of electron that is local to your project, within the `node_modules`.

I would suggest `rm -rf node_modules && npm install` in the newly copied directory, in case there were somehow some hardcoded full paths in your previous directory.

If that doesn't work, can you publish your code somewhere so we can take a look?

**Comment by quantumproducer** [comment]
Yes, that fixed it, thanks @zeke & @jlord !
Justh ad to rm -rf node_modules. 

Btw this tool works great for making cross platform local multiplayer games. TY!

**Comment by zeke** [comment]
Glad that worked out, @quantumproducer. Thanks for following up and closing the issue!
